### ISSUE TITLE
Fix GitHub codespace config

### ISSUE THREAD

**Issue by noah-schechter** [atlosdotorg/atlos#972]
**Repro**
1. Create a new GitHub codespace 
2. Enter the `platform` directory
3. Run `mix phx.server`

**Expected**
Atlos should begin running without errors.

**Current**
Atlos begins running with the following errors:
```
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /workspace/platform/assets/postcss.config.js

(@/workspace/platform/assets/postcss.config.js)
    at load (/home/vscode/.npm/_npx/bc7494899bbce1ca/node_modules/postcss-load-config/src/plugins.js:28:11)
    at /home/vscode/.npm/_npx/bc7494899bbce1ca/node_modules/postcss-load-config/src/plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (/home/vscode/.npm/_npx/bc7494899bbce1ca/node_modules/postcss-load-config/src/plugins.js:52:8)
    at processResult (/home/vscode/.npm/_npx/bc7494899bbce1ca/node_modules/postcss-load-config/src/index.js:38:14)
    at /home/vscode/.npm/_npx/bc7494899bbce1ca/node_modules/postcss-load-config/src/index.js:168:14
    at async loadPostCssPlugins (/home/vscode/.npm/_npx/bc7494899bbce1ca/node_modules/tailwindcss/lib/cli/build/plugin.js:60:12)
    at async createProcessor (/home/vscode/.npm/_npx/bc7494899bbce1ca/node_modules/tailwindcss/lib/cli/build/plugin.js:226:74)
    at async build (/home/vscode/.npm/_npx/bc7494899bbce1ca/node_modules/tailwindcss/lib/cli/build/index.js:39:21)
15:09:24.253 [error] Task #PID<0.679.0> started from PlatformWeb.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix 1.7.10) lib/phoenix/endpoint/watcher.ex:55: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["npx", ["tailwindcss", "--input=css/app.css", "--output=../priv/static/assets/app.css", "--postcss", "--watch", {:cd, "/workspace/platform/assets"}]]
```

**Comment by milesmcc** [comment]
Hmm. Seems like the post create command isn't running.

**Comment by milesmcc** [comment]
(The issue appears to be that `npm install` has not been run in the `platform/assets` directory.)
